'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/app/contexts/SessionContext";
import { Toaster } from 'react-hot-toast';
import { Navbar } from "@/app/components/Navbar";
import { AppProvider, useAppContext } from "@/app/contexts/AppContext";
import { Dish } from "@/app/components/DishCard";
import { Restaurant } from "@/app/components/RestaurantCard";
import { NavbarWrapper } from "@/app/components/NavBarWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// function NavbarWrapper() {
//   const {
//     selectedCity,
//     setSelectedCity,
//     selectedTab,
//     setSelectedTab,
//     handleAddDish,
//     handleAddRestaurant
//   } = useAppContext();
//
//   return (
//       <Navbar
//           selectedCity={selectedCity}
//           onCityChange={setSelectedCity}
//           selectedTab={selectedTab}
//           onTabChange={setSelectedTab}
//           onAddDish={handleAddDish}
//           onAddRestaurant={handleAddRestaurant}
//       />
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <AppProvider>
            <Toaster position="top-right" />
            <NavbarWrapper />
            {children}
          </AppProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
