server:
  port: ${GATEAWAY_PORT:8082}

spring:
  application:
    name: api-gateway

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/foodapp}
    username: ${DB_URL:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: foodapp
              uri: http://${BACKEND:localhost}:8081
              predicates:
                - Path=/api/foodapp/**
              filters:
                - RewritePath=/api/foodapp/(?<segment>.*), /api/${segment}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO

token:
  signing:
    key: ${SIGN_KEY:mySecretSigningKey123456789012345678901234567890}

cors:
  allowedOrigins : http://localhost:3000,http://${SERVER_IP}:3000