server:
  port: 8082

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:postgresql://31.97.231.63:5433/foodapp
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: foodapp
              uri: http://localhost:8081
              predicates:
                - Path=/api/foodapp/**
              filters:
                - RewritePath=/api/foodapp/(?<segment>.*), /api/${segment}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO

token:
  signing:
    key: mySecretSigningKey123456789012345678901234567890
